#ifndefsDESIGN_PATTERNS_STACK_MACHINE_CODE_GENERATOR_H
#definesDESIGN_PATTERNS_STACK_MACHINE_CODE_GENERATOR_H

class StackMachineCodeGenerator : public CodeGenerator {
};

#endif /* STACK_MACHINE_CODE_GENERATOR_H */
